export const THANK_YOU = "Thank you for visiting my profile"
export const LOWES = "Lowe's"
export const ABOUT_DES_ONE = "Hi, I am a software developer with 6+ years of experience in retail and e-commerce."
export const ABOUT_DES_TWO = "While I have worked as a full-stack developer, my strength is front-end development, where I build user-friendly and high-performance web applications. I enjoy creating scalable solutions that improve digital experiences."
export const ABOUT_DES_THREE = "Feel free to reach out if you'd like to connect or discuss opportunities!"
export const ROLES = "Software Engineer at H&M Group | Ex-Lowe's"